### ISSUE TITLE
FR5.  Merge Two Separate PDFs 

### ISSUE THREAD

**Issue by Coveted8749** [UNO-CSCI4830/legalPDF#11]
|FR5.  Merge Two Separate PDFs |
|---|
|**Goal**: The program can take two pdfs and combine them into a single PDF.
**Stakeholders:** Legal Firm, Legal Firm Clients, Independent Customers, Users of the free product, Software Developers|
| **Description:** The user will provide the two PDFs. The program takes both of those PDFs and returns them as a single PDF with all the pages of both PDFs included.  |
| **Origin:** Requirement identified during the project proposal.|
| **Version:** 1.0  |  
|**Date:** 09/2/2024  
|  **Priority:** 1 |

**Comment by Coveted8749** [comment]
This issue works. There are a few edge cases that need to be resolved.

**Comment by jwischmeier** [comment]
This is working consistently.
