### ISSUE TITLE
NFR3 Portability

### ISSUE THREAD

**Issue by jwischmeier** [UNO-CSCI4830/legalPDF#16]
|NFR3.|
|---|
|**Goal**: Portability
**Stakeholders:** Legal Firm, Legal Firm Clients, Independent Customers, Users of the free product, Software Developer|
| **Description:** The program should be portable across any desktop application using the chrome browser, allowing users to run it on their preferred devices. |
| **Origin:** Meeting number 1|
| **Version:** 1.0  |  
|**Date:** 09/25/2024  
|  **Priority:** 3 |

**Comment by Coveted8749** [comment]
So far it only works as html pages on a desktop, but is not portable into the extension.

**Comment by Coveted8749** [comment]
Successfully works in the extension
