### ISSUE TITLE
FR15. Watermark

### ISSUE THREAD

**Issue by gjayaun1** [UNO-CSCI4830/legalPDF#17]
|FR15.  Watermark|
|---|
|Goal: Create a custom watermark stamp that will display on each page once the PDF is downloaded to the user’s device. Stakeholders: Free Customers|
| Description: When a free user is finished editing the document there should be a watermark that displays on each page with our groups name of choosing. This would incentivize users to opt in for a paid version that removes the watermark while also advertising our extension to outside sources that may see the watermark.  |
| Origin: Came up with on 3rd meeting after discussing two different paid and free versions.|
| Version: 1.0  |
|Date: 09/29/2024
|  Priority: 15 |

**Comment by jwischmeier** [comment]
This will not be added during this work session.
