### ISSUE TITLE
FR6. SPLIT PDF

### ISSUE THREAD

**Issue by diomoreno** [UNO-CSCI4830/legalPDF#22]
|FR6. SPLIT PDF|
|---|
|**Goal**: The program can split an existing PDF into two separate PDF files.|
**Stakeholders:** Legal Firm, Legal Firm Clients, Independent Customers, Users of the free product, Software Developers|
| **Description:** When a customer wants to have two separate PDF files they may split a PDF into two files for proper arranging, organizing, or managing. They can specify page ranges. Example: A 100 page PDF file can be turned into five 20-page PDF files. |
| **Origin:** Meeting number 1|
| **Version:** 1.0 |
|**Date:** 09/19/2024
| **Priority:** 6 |

**Comment by Coveted8749** [comment]
This will not be an implemented feature. However, the customer will be able to either print the pdf to save as pdf using the existing chrome structure.
