### ISSUE TITLE
FR7.  Delete 

### ISSUE THREAD

**Issue by diomoreno** [UNO-CSCI4830/legalPDF#23]
|FR7.  Delete|
|---|
|**Goal**: The program can cut pages off of a single PDF file and return a new PDF file with the remaining pages.|
**Stakeholders:** Legal Firm, Legal Firm Clients, Independent Customers, Users of the free product, Software Developers|
| **Description:** Users can choose one or several pages to delete by specifying numbers or selecting them. This helps eliminate clutter by getting rid of blank pages, duplicate pages, or irrelevant information from the PDF which results in more concise and relevant information being presented. |
| **Origin:** Requirement identified at meeting two|
| **Version:** 1.0 |
|**Date:** 09/25/2024
| **Priority:** 7 |

**Comment by Coveted8749** [comment]
Works on the extension.
